[General]
db_name = dns_lookup_results.db
status_file_dir_name = status_updates
dns_checker_script_name = dns_checker.py
whois_script_name = run_whois_lookup.py
domains_input_file = domains.txt

[DNSChecker]
successful_nameserver_patterns = godaddy.com
unsuccessful_nameserver_patterns = sedoparking.com, parkingcrew.net, domainsponsor.com, bodis.com
default_record_types_to_check = NS, A, AAAA, MX, SOA, TXT
check_srv_records = true
check_caa_records = true
check_email_auth_records = true
# Optional: common SRV prefixes if desired
srv_prefixes_to_check = _sip._tcp, _xmpp-client._tcp 
default_retries = 3
default_timeout_seconds = 5
default_lifetime_seconds = 10

[WHOIS]
whois_api_base_url = https://api.com/
api_retries = 3
api_retry_delay_seconds = 5
privacy_keywords = privacy_keywords = Privacy Protect, Domains By Proxy, WhoisGuard, Contact Privacy, REDACTED FOR PRIVACY, Private Registration, Anonymized, DATA REDACTED, Whois Privacy, See PrivacyGuardian.org, Whois privacy services, Domain Privacy, Privacy Service, Identity Protection, Guard Privacidad, Privacy Service Provided, Jewella Privacy LLC, JewellaPrivacy.com
